kkebo/swift-syntax

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-06-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-03-06-a

.github/workflows/test.yml
The unit test has been broken since #7. I overlooked that.
https://github.com/kkk669/swift-syntax/pull/7#issuecomment-1981503267
=> ci: fix unit test

.github/workflows/test.yml
This action is official and has the advantages of simplifying the steps.
=> ci: use the bytecodealliance/actions/wasmtime/setup action

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-26-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-26-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-27-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-27-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-28-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-28-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-29-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-04-29-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-02-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-02-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-24-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-24-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-25-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-05-25-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-05-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-05-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-07-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-07-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-08-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-08-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-14-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-06-14-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-07-10-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-07-10-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-07-16-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-07-16-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-08-30-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-08-30-a

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-07-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-07-a

.github/workflows/test.yml
I've used the latest wasmtime in the CI, but that sometimes broke the CI, so I'm going to pin its version.
=> ci: pin wasmtime version to 24.0.0

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-20-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-20-a

.github/workflows/test.yml
- https://github.com/bytecodealliance/wasmtime/releases/tag/v25.0.0
- https://github.com/bytecodealliance/wasmtime/releases/tag/v25.0.1
=> ci: bump wasmtime to 25.0.1

.github/workflows/test.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-26-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-09-26-a

.github/workflows/swiftwasm.yml
This will help differentiate this file from the upstream's workflow files when they are added in the future.
=> chore: rename test.yml to swiftwasm.yml

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v25.0.2
=> ci: bump wasmtime to 25.0.2

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-15-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-15-a

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v26.0.0
=> ci: bump wasmtime to 26.0.0

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-27-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-27-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-28-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-28-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-S NAPSHOT-2024-10-31-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-10-31-a

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v26.0.1
=> ci: bump wasmtime to 26.0.1

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v27.0.0
=> ci: bump wasmtime to 27.0.0

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-21-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-21-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-24-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-24-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-29-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-29-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-30-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-11-30-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-05-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-05-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-17-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-17-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-20-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-20-a

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v28.0.0
=> ci: bump Wasmtime to 28.0.0

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-23-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2024-12-23-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-04-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-04-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-06-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-06-a

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v28.0.1
=> ci: bump wasmtime to 28.0.1

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-11-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-01-11-a

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v29.0.0
=> ci: bump wasmtime to 29.0.0

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v29.0.1
=> ci: bump wasmtime to 29.0.1

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-02-07-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-02-07-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-02-18-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-02-18-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-04-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-04-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-14-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-14-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-17-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-17-a

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v31.0.0
=> ci: bump wasmtime to 31.0.0

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-25-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-25-a

.github/workflows/swiftwasm.yml
swiftlang/swift:nightly-main-noble is now available, so I updated the image used in CI to it.
=> ci: use noble image

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-28-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-03-28-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-04-03-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-04-03-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-04-12-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-04-12-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-12-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-12-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-14-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-14-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-29-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-05-29-a

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-06-17-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-06-17-a

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v34.0.0
=> ci: bump wasmtime to 34.0.0

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v34.0.2
=> ci: bump wasmtime to 34.0.2

.github/workflows/swiftwasm.yml
https://github.com/swiftwasm/swift/releases/tag/swift-wasm-DEVELOPMENT-SNAPSHOT-2025-07-18-a
=> ci: bump Swift SDK to swift-wasm-DEVELOPMENT-SNAPSHOT-2025-07-18-a

.github/workflows/swiftwasm.yml
https://github.com/bytecodealliance/wasmtime/releases/tag/v35.0.0
=> ci: bump wasmtime to 35.0.0

.github/workflows/swiftwasm.yml, Scripts/ci-install-swiftly.sh
Pros:
- We can use the latest nightly toolchain as soon as possible.
- We no longer need to worry about the gzip issue.
Cons:
- CI execution time is a little bit longer.
=> ci: use swiftly instead of swiftlang/swift images

.github/workflows/swiftwasm.yml
Swift SDK for Wasm is now published on swift.org, but it doesn't seem to have an SDK for wasm32-wasip1-threads.
=> ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-07-23-a_wasm
