kkebo/swift-syntax

.github/workflows/test.yml

The current stack size is too large, so I'd like to shrink it as small as possible.

ci: reduce stack size

---

Release Notes/600.md
Release Notes/601.md
Sources/SwiftIDEUtils/FixItApplier.swift
Sources/SwiftParser/IncrementalParseTransition.swift
Sources/SwiftSyntax/SourceEdit.swift
Sources/SwiftSyntax/Utils.swift
Sources/_SwiftSyntaxTestSupport/IncrementalParseTestUtils.swift
Tests/SwiftParserTest/SequentialToConcurrentEditTranslationTests.swift
Tests/SwiftSyntaxTestSupportTest/IncrementalParseTestUtilsTest.swift

- **Merge `SourceEdit` and `IncrementalEdit`**
- **Remove some whitespaces**
- **Add release note for deprecated `IncrementalEdit`**

Merge upstream/main into wasm32-wasi-test

---

.github/workflows/swiftwasm.yml

https://github.com/bytecodealliance/wasmtime/releases/tag/v30.0.0

ci: bump wasmtime to 30.0.0

---

.github/workflows/swiftwasm.yml

https://github.com/bytecodealliance/wasmtime/releases/tag/v30.0.2

ci: bump wasmtime to 30.0.2

---

.github/workflows/swiftwasm.yml

https://github.com/orgs/community/discussions/148648

ci: use GitHub-hosted arm64 Linux runners

---

.github/workflows/swiftwasm.yml

https://github.com/bytecodealliance/wasmtime/releases/tag/v32.0.0

ci: bump wasmtime to 32.0.0

---

.github/workflows/swiftwasm.yml

This PR is intended to match the style to kkebo/swift-format.

ci: change from snake_case to kebab-case

---

.github/workflows/swiftwasm.yml

https://github.com/bytecodealliance/wasmtime/releases/tag/v33.0.0

ci: bump wasmtime to 33.0.0

---

.github/workflows/swiftwasm.yml

context: https://github.com/orgs/community/discussions/26822

ci: add `results` job for required status checks

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/c0c57bffc5233cc623d91467a3ca33ce2a4e6671

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-07-26-a_wasm

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/7d69b826cbd0c0e2448695f317f10191a79e3347

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-05-a_wasm

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/2d8aaf9f936622b27069537258f8f9e72a0583dd

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-08-a_wasm

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/fc2ec3e025405d4a96f787240f196c4f7ec0b2e0

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-10-a_wasm

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/15c6b598ee8c36c26bbe690dd5d8b6842d2b3ad7

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-14-a_wasm

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/b5b1a40000227bafbc6f36f12ebcf8c09b4cee0a

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-23-a_wasm

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/1e9e927abf16ca947e9e1890fe9d444765773879

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-08-25-a_wasm

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/d73744459e86dcdf4df779f99227408d2f0df026

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-09-12-a_wasm

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/c9bafa900c3c4c865291bf94881ceab9813c770b

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-09-13-a_wasm

---

.github/workflows/swiftwasm.yml

https://github.com/swiftlang/swift-org-website/commit/3c962141480541055c8a920c2dc7f0ab4ff79587

ci: bump Swift SDK to swift-DEVELOPMENT-SNAPSHOT-2025-09-19-a_wasm

---

Scripts/ci-install-swiftly.sh

See https://www.shellcheck.net/wiki/SC1090.

ci: refactor shellcheck comment
